CREATE TABLE CAR_INFO(
	CAR_NUMBER INT AUTO_INCREMENT PRIMARY KEY
	, CAR_NAME VARCHAR(10)
	, CAR_PRICE INT NOT NULL
	, CAR_MAKER_NUMBER INT NOT NULL -- 1: 현대 2: 기아 3: 쌍용
);

DROP TABLE car_info;

DROP TABLE sales_info;

COMMIT;

SELECT *
FROM car_info;

SELECT * 
FROM sales_info;

CREATE TABLE SALES_INFO (
	SALES_NUMBER INT AUTO_INCREMENT PRIMARY KEY
	, CUSTOMER_NAME VARCHAR(20) NOT NULL
	, CUSTOMER_TEL VARCHAR(30)
	, SALES_COLOR VARCHAR(3) NOT NULL
	, SALES_DATE DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
	, CAR_NUMBER INT REFERENCES CAR_INFO(CAR_NUMBER)
);

DELETE FROM sales_info WHERE SALES_NUMBER = 7;

INSERT INTO SALES_INFO (
   CUSTOMER_NAME
   , SALES_COLOR
   , CUSTOMER_TEL
   , CAR_NUMBER
) VALUES (
	'홍길동',
	'화이트',
	'010-1111-2222',
	7
        );